/**
 * One-off script: generates public/roadmap.json from the clean fixture.
 * Used only during Phase 02 to produce a committed placeholder snapshot.
 * The real snapshot is generated by pnpm sync:snapshot (requires LINEAR_API_KEY).
 */
import { writeFileSync } from "node:fs";
import { buildSnapshot } from "./linear/transform.ts";
import { rawClean } from "./linear/__fixtures__/raw-clean.ts";

const snap = buildSnapshot(rawClean, { now: "2026-06-26T00:00:00Z" });
writeFileSync("public/roadmap.json", JSON.stringify(snap, null, 2));
console.log("Placeholder public/roadmap.json written from clean fixture.");
